[package]
name = "midi2json"
version = "0.1.0"
authors = ["Andrew Jensen <andrewjensen90@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
midly = "0.1.3"
clap = "2.33.0"
